### ISSUE TITLE
1.7.0 and 1.7.1 doesnt fix fake datas

### ISSUE THREAD

**Issue by kiler2010** [kakysha/HonorSpy#101]
Hello. Honor spy still have fake players and honor after clearing all data from table.
https://imgur.com/XWQ3nVr

**Comment by Nelythia** [comment]
Probably because people did not update yet and share you their non updated data table.

Tell them to update.

**Comment by kakysha** [comment]
@Nelythia shouldn't be the case, as if you already checked one name, it got marked as 'fake' or 'good' forever. So you will instantly discard the rows which you already checked and proved to be fake.

On another course, the checking process is long enough, which can be paused or stuck and continues after relog / reload or when new data got pushed to you. Simply speaking, it takes time. Without pauses it goes for 1 player check per second.

**Comment by Godmatik** [comment]
While it cleared the majority of fake entries for me, it still did not clear one of them on our server, it has been up there for the past day and everyone else sees it still so it's not just a matter of waiting, and I believe the reason was that it is an actual character name that I am able to add to my friends list.

Perhaps we can filter and ignore results from those below level 10, or something similar? Otherwise, if there was a way for us to manually blacklist a name for our own purposes, that would be fantastic.

**Comment by Rush1988** [comment]
@Godmatik If it's possible, filter level 60 in my opinion. 10 is being far too generous.

**Comment by rpbailey-dm** [comment]
As someone who works with large datasets regularly in a professional setting I think there are a couple of things you could do to eliminate 99% of tampering.

First would be that you cannot add your own honor data to the database, someone else has to see yours in order for it to be added.

Second would be that 2 people have to see it to add the entry to the list.

The current fake player and good player list in combination with these other two things would eliminate the vast majority of tampering.

Also, if there is a way to obfuscate the data in the WTF folder that contains the database information, this would also be a good thing to do. Currently you can edit the database file and change the unix stamp to send out bogus honor amounts as well.

**Comment by jwagz2000** [comment]
Now currently it appears someone has created an ability to spoof data with a mouse over ability we currently have duplicates of over 1000 in the DB that have all 9999992 honor which none of them have
