### ISSUE TITLE
Custom pool size

### ISSUE THREAD

**Issue by wlfbck** [kakysha/HonorSpy#107]
It would be great if we could set a custom pool size in the options. Reasons should be obvious; we already have an estimate for the usual pvp pop on our server, honorspy ofc doesn't "know" that. Makes it easier to guesstimate where you will land, etc. 

I assume pop size itself is not shared anyway between clients, just the actual table of players, should make this relatively easy.

**Comment by kakysha** [comment]
Whats wrong with HonorSpy estimations?

**Comment by wlfbck** [comment]
Nothing is wrong, but just by the nature of what information is available it's estimate is usually much lwoer than the actual pvp population. That's why if i can specify it myself it allows me to estimate some stuff more easily.

**Comment by kakysha** [comment]
to get your estimation, you need to know your position in table, so how will you know that if HonorSpy has much less pool size for you?
And its better to find the reason why HonorSpy has non-realistic pool size, as it seems to be not the case for mose of players, only for you?

**Comment by wlfbck** [comment]
Because there is always a lot of people who will get like 15HKs in wpvp while leveling or who only pvp for like an hour. They will not be anywhere at the top ;)

Not only for me, everyone on my server. Usually misses like 500 people. Dreadmist-EU.

To my knowledge you can only sync via g/p/ra right?

**Comment by Binkcn** [comment]
*My English is not good. With the help of Google Translate, I hope you can understand.*

I also have the same problem. The total number of players recorded in the local database of the plug-in is about 1500+, and the maximum `Standing` of players in the plug-in record has exceeded 7000+. According to the BR14 rule 0.003, only the top 5 players belong to BR14, but in fact The entire server should have at least 21 players entering BR14.

I originally wanted to try to modify this problem, but this problem seems very troublesome, because not all players are available in the local database, so the interval cannot be accurately divided.

**Comment by mcd8604** [comment]
> to get your estimation, you need to know your position in table, so how will you know that if HonorSpy has much less pool size for you?

Most often, the upper brackets (e.g. 14 through 10) are filled out completely because the players are on for such long time periods and are extremely likely to be inspected. These players are likely using this addon and thus will know where they lie in relative honor / current standing.

> And its better to find the reason why HonorSpy has non-realistic pool size, as it seems to be not the case for mose of players, only for you?

The lower brackets are relatively huge in size, have players that are only on for short periods of time each week, and the players are less likely to be using the addon. For these reasons, the likelihood of lower bracket players being in any user's DB is lower. The fact that there are many more of these players exaggerates the issue.

Because the observed pool size on my server is usually about 2000 under the actual, the bracket sizes are way off. Unfortunately, I have to completely disregard the estimations from HonorSpy. I actually read in the honorspy database into a separate app which I then use to calculate estimations and other various metrics. This is mainly because I can input my own estimated pool size and perform post-processing on the data.

**Comment by Binkcn** [comment]
> > to get your estimation, you need to know your position in table, so how will you know that if HonorSpy has much less pool size for you?
> 
> Most often, the upper brackets (e.g. 14 through 10) are filled out completely because the players are on for such long time periods and are extremely likely to be inspected. These players are likely using this addon and thus will know where they lie in relative honor / current standing.
> 
> > And its better to find the reason why HonorSpy has non-realistic pool size, as it seems to be not the case for mose of players, only for you?
> 
> The lower brackets are relatively huge in size, have players that are only on for short periods of time each week, and the players are less likely to be using the addon. For these reasons, the likelihood of lower bracket players being in any user's DB is lower. The fact that there are many more of these players exaggerates the issue.
> 
> Because the observed pool size on my server is usually about 2000 under the actual, the bracket sizes are way off. Unfortunately, I have to completely disregard the estimations from HonorSpy. I actually read in the honorspy database into a separate app which I then use to calculate estimations and other various metrics. This is mainly because I can input my own estimated pool size and perform post-processing on the data.

Hi brother, you can try my modified version, it can estimate the next ranking more accurately when receiving less data.

https://github.com/Binkcn/HonorSpy
