### ISSUE TITLE
adding random players to friends list

### ISSUE THREAD

**Issue by d3aths** [kakysha/HonorSpy#130]
using the latest version. keeps adding randoms to my friends. everytime i remove a person it seems to have added them back next time i login.
i read its supposed to remove them automatically but this doesn't happen.

**Comment by kakysha** [comment]
addon adds friends with a note "Honorspy checking", check if there is such note on those added friends. If there is no note, probably its not HonorSpy. And if there is, its a bug.

**Comment by d3aths** [comment]
yep, the note on the added player does say that its honorspy

**Comment by perfectstormie** [comment]
Yeah this is a bugg, im getting whispers now from alot! of people stating im a cheater etc and reporting me cause they are afraid someone is messing with their account... please fix this!

**Comment by shkabo** [comment]
My guild mate had similar issue so I quick peaked into the code. Addon has something called "Fake Players Filter" which works by adding players from your realm/faction to the friend list and removing it afterward. Bug probably happens when player logsoff while addon is doing checkup. Developer should add friends list checkup and removing all those random people from friend list when user logs on.
This is the filter https://github.com/kakysha/HonorSpy/blob/classic/honorspy.lua#L452

**Comment by shkabo** [comment]
Quickfix for all, open `~\World of Warcraft\_classic_\Interface\AddOns\honorspy` file `honorspy.lua` and after line 47 add `HonorSpy:removeTestedFriends()`, save and reload UI

**Comment by kakysha** [comment]
@shkabo your fix will not work, as `HonorSpy:removeTestedFriends()` is called on every addon load (check `DBHealthCheck()`, which is literally called on the line before your fix , and is called constantly when new players added to database (which happens all the time you play the game).

Also, just do a proper PR here next time and I release your fix for everyone, if you really want to help.

I believe this is some sort of Blizzard API bug, and its certainly only affecting players with super short names, its always one unlucky guy which is not deleted for some reason.

**Comment by teerzo** [comment]
Same issue, my character name is "Te". Started getting whispered nonstop by players wondering why i was on their friendslist

**Comment by TpsArchyy** [comment]
2024 and the fucking bug is still there, is anyone working on this fucking addon anymore? every fucking day i find people on my friends list with "honorspy testing" tag... ffs fix your shit or remove that fucking functionality from the addon

**Comment by Slivo-fr** [comment]
Good evening,

It was fixed in 2020 as far as I know
Which version of the addon and which version of the game to you have issue with ?

What is your use case for honorspy in 2024 ?

The addon is now useless on classic ERA and I don't think it has any purpose elsewhere
Unless I am mistaken, the addon is not maintained anymore because it has no purpose anymore

**Comment by TpsArchyy** [comment]
Version: 1.9.4-classic using it on SoD version of the game.

**Comment by Slivo-fr** [comment]
I will need more detail about SOD then.
This addon doesn't support any season of whatever

Is there a ranking system in SOD ? Is it fixed amount of honor just like ERA or did blizz try to do some fancy things here ?

**Comment by TpsArchyy** [comment]
i dont wanna be a asshole mate but dont have the time for this, gave you the addon version and on what version of the game is used, can you update that version so that the "friend" bug is fixed? if not i will just remove it and be done with it.

**Comment by Slivo-fr** [comment]
Well then, I guess the answer you are looking for is: This addon does not support SOD

**Comment by TpsArchyy** [comment]
very good then, i will uninstall it. Thank you for the info, have a nice day.
