### ISSUE TITLE
Why don't you just add a release?

### ISSUE THREAD

**Issue by Ezzpify** [kakysha/HonorSpy#14]
Instead of cloning the whole repo

**Comment by kakysha** [comment]
Just because, basically, every commit = new release. Nothing bad in cloning the repo besides that "-master" suffix :)

**Comment by Ezzpify** [comment]
You understand the purpose of GitHub implementing a release section?

**Comment by kakysha** [comment]
Just because it exists it doesn't mean it is suitable for every case. For HonorSpy it is not, as I push commits rarely and only when done with testing locally.
WoW, unfortunately, can't update your addons, neither there is any addons managers that rely on semver. I see no benefits of using releases, only downside of making zip archives and uploading same  pack of files already presented on GitHub with every push I do.
Am I missing smth @Ezzpify ?

**Comment by joks18** [comment]
@Ezzpify  steam authenticator no trade work pliz help me ..
