### ISSUE TITLE
Still lag spikes / mini freezes in battlegrounds

### ISSUE THREAD

**Issue by Finrodi** [kakysha/HonorSpy#17]
Hey,

I am using the most recent version (v3) but still experience horrible lag spikes / mini freezes when the addon is enabled - putting it on standby fixes it. I assume the data is just too big and gets synced every time you or a teammate with honorspy dies? Currently with over 8800 people in my weekly list (playing on Northdale) it really makes it almost impossible to play properly with the addon enabled. Would be awesome if you can somehow fix this issue, a lot of people confirmed the same issue with honorspy despite it being an absolute awesome addon.

PS: Currently when we die in a bg it gives an even bigger freeze (expected), would be nice tho if the sync could be delayed by a second or two so we can properly see what killed us / what happened.

**Comment by kakysha** [comment]
Appreciate your expressive feedback. As you correctly noticed, lag spikes prolly caused because of huge bandwidth being synced across players. Delaying sync by couple of seconds will just delay lags and wont solve the problem. And I really do want to solve this.

So, the first and obvious solution coming to my mind is to somehow limit number of rows being synced. At this stage you guys can help me with conditions on which to filter rows which addon should sync. Prolly the best option would be to sync incrementally: sync the whole data after first death, then only sync updated rows.

**Comment by Finrodi** [comment]
Sure, just let me know when u need my help!
