### ISSUE TITLE
Mouseover inspects causing issues with manual inspect & RealmPlayers collection

### ISSUE THREAD

**Issue by Citano** [kakysha/HonorSpy#18]
If you mouseover with a manual inspection open and manage to mouseover someone else, then data of character gets changed (as intended). 
You can probably also understand that at times this can be an unwanted situation if you want to actually check someone out with inspection.

Also, having honorspy makes data collecting for RealmPlayers armory alot more difficult. Even when pressing "Target Nearest Friend" keybind or a macro with "TargetNearestFriend()" included there have been times when a player has not been collected for VF_RealmPlayers. 
Disabling Honorspy removes this issue for both inspections and RealmPlayers armory data collection.

I could just edit the addon myself for my own personal preferences, but my suggestion is to perhaps have a toggle/option to disable/enable mouseover data collection for HonorSpy, with it being enabled by default.

EDIT: After I manually removed any mouseover functions and despite realmplayers armory data got better, its still better when the addon is disabled. Perhaps there is something related to when the addon calls for clearing stuff when inspecting target. Especially gathering data for players on the move or when you yourself are on the move is problematic.

**Comment by kakysha** [comment]
First of all, do you have latest HonorSpy version?
Because I did workarounds for both of these two cases you mentioned:
https://github.com/kakysha/HonorSpy/blob/master/honorspy.lua#L23 - for RealmPlayers
https://github.com/kakysha/HonorSpy/blob/master/honorspy.lua#L182 - for inspection

Check if you have that lines in your code. 
While you open `inspect player` window, HonorSpy just get paused untill the window is closed.
For RealmPlayers, it delays RealmPlayers inspection until HS done inspecting, then calls RealmPlayers inspection again. It is not related to mouseover stuff. It is how both addons work - as Vanilla WoW only allows requesting info about one player at a time (current target), there is no way to make both addons work independently and simultaneously.

**Comment by Citano** [comment]
I have the newest version for HonorSpy. Even reinstalled it to make sure.
Here is what happens if you inspect someone but have your mouseover be on other players. Look at how the honor information changes as soon as the mouseover finds a new target.
[![Screenshot from Gyazo](https://gyazo.com/58621f9fcb31f8a3928ba4ecbe0642a5/raw)](https://gyazo.com/58621f9fcb31f8a3928ba4ecbe0642a5)

Regarding Realmplayers armory data, here is what happens with Honorspy enabled.
[![Screenshot from Gyazo](https://gyazo.com/aa1dd7e6f096a07b82aaa8abac1d49b6/raw)](https://gyazo.com/aa1dd7e6f096a07b82aaa8abac1d49b6)
Here I tried to tab target 10 times and none of the ones I target in close range gets stored.

Then I disable Honorspy and try once more:
[![Screenshot from Gyazo](https://gyazo.com/97b53e813f2a9b25d1cf273a94bb5905/raw)](https://gyazo.com/97b53e813f2a9b25d1cf273a94bb5905)
Here, I target 9 players and 1 NPC and the players all get stored successfully as you can see in the chat.

So there is something both preventing inspections from working as intended because of mouseover function in Honorspy (and perhaps other functions too) and Realmplayers data collection being prevented or slowed too much to be usable.
