### ISSUE TITLE
old version fucking it up for everyone

### ISSUE THREAD

**Issue by greath2217** [kakysha/HonorSpy#33]
can you make it so that ppl that still use an older version cant send honor values to ppl that have the new version?

i am still getting duplicates because some ppl havent updated their version yet

**Comment by kakysha** [comment]
I did exactly that with v1.2.0
You still get duplicates because those who updated to v1.2.0 (including you) have their corrupted database from old versions.
It will be automatically fixed on Wednesday when week is reset and all data is wiped. Nothing I can do with it for now, sadly. We just need to wait 2 days.
