### ISSUE TITLE
Honor spy lost all data and didnt show me anything!

### ISSUE THREAD

**Issue by showyk** [kakysha/HonorSpy#62]
today, after the weekly reset of the honor and ranks, my honor spy just stopped to register the data and lost all my data.
![image](https://user-images.githubusercontent.com/58238913/69684424-65aa7f00-1097-11ea-9c36-5b4e8bcd53c5.png)

**Comment by Nelythia** [comment]
That is how HonorSpy works. It resets your data after each Honor calculation because there is no point to keep your old data. To make reliable estimates like pool size, your standing, your next rank, etc it has to work like this.

It will update people with 15 HK's and their honor each day after the 24h reset. That is how Blizzards honor tab works in 1.13, compared to privateserver where it updated on every inspect.

**Comment by showyk** [comment]
Oh, i will wait till tomorrow to see if its back to normal.
Thanks for your reply Nelythia
