### ISSUE TITLE
Database has data from previous Week

### ISSUE THREAD

**Issue by Kelran123** [kakysha/HonorSpy#98]
Got seeded a lot of data from the previous week.
Addons says it resets every Wednesday somehow that didnt work for everyone.

I think a nice workaround would be a procedure which clears data older than last reset once a day or with a button click.

Greetings

**Comment by kakysha** [comment]
which server / region / addon version?

**Comment by Kelran123** [comment]
Hi,
i am running Honorspy 1.6.7. i check for updates daily with twitch client.

Server Heartstriker (German PVP-Server) / EU / 1.6.7.

I was looking through your code a little bit. Seems like your code should cover what i was suggesting in the playerIsValid() function but i dont know lua 

I am trying to figure out if i can trigger Addon functions over macros but i don´t  think its possible. Was trying to trigger DBHealthCheck

**Comment by Kelran123** [comment]
Maybe the problem is with people who play on different PCs?
Wednesday is weekly reset.
When i play on PC1 on Reset day it resets Honorspy
Then i log on PC2 on Thursday and already have Honor this week then it doesnt reset my Honorspy on PC2 ?

Somehow i think that is how your code is by reading throug it?

Greetings and nice Christmas

**Comment by kakysha** [comment]
Good catch! Definitely that can be the case. I'll dig into it.

**Comment by teelolws** [comment]
Yeah theres something up with it. Reset was two days ago. Theres data from the previous week. https://cdn.discordapp.com/attachments/617633049147998209/659676359022608392/unknown.png

I'm pretty sure they're all people who either haven't logged in since the reset or none of my guildies/people in my BGs have seen them but they're sharing dud data with me that my addon is just accepting.

**Comment by teelolws** [comment]
I think there is something up with this bit:

`or player.last_checked < HonorSpy.db.factionrealm.last_reset + 24*60*60`

Is `HonorSpy.db.factionrealm.last_reset` supposed to be 0?

Edit: Ahhh its because I reset my addon settings, and it only sets the following week. Still though, the data should never have been shared with me to begin with. It should have been purged from the other players databases first.

**Comment by dinkmaster** [comment]
Same issue here, before reset I was playing on PC1, after reset first day I logged on PC2 only then 2nd day past reset I logged on PC2 and the data was from previous week for a lot of people

**Comment by kakysha** [comment]
Should be fixed now
